In [3]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().resolve()
while PROJECT_ROOT.name != 'crawl_data_phone in cellphones' and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent

PHONE_SPECS_PATH = PROJECT_ROOT / 'data' / 'raw' / 'phone' / 'phone_specs.csv'
URL_FINAL_PATH = PROJECT_ROOT / 'data' / 'raw' / 'url' / 'url_final.csv'

f:\Anaconda\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
f:\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [41]:
df = pd.read_csv(PHONE_SPECS_PATH)

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Tên sản phẩm         11 non-null     str
 1   Giá bán              11 non-null     str
 2   RAM                  10 non-null     str
 3   Bộ nhớ trong         10 non-null     str
 4   Kích thước màn hình  11 non-null     str
 5   Tấm nền              10 non-null     str
 6   Tần số quét          9 non-null      str
 7   Độ phân giải         9 non-null      str
 8   Dung lượng pin       11 non-null     str
 9   Chip xử lý           11 non-null     str
 10  Hãng sản xuất        11 non-null     str
 11  Hệ điều hành         10 non-null     str
 12  Camera trước         10 non-null     str
 13  Camera sau           10 non-null     str
 14  Quay video           7 non-null      str
 15  Sạc nhanh            10 non-null     str
 16  Kháng nước / bụi     7 non-null      str
 17  Trọng lượng          8 non-null      str
 18  Khuyến mãi giảm giá  9 non-null      str
 19  URL                  11 non-null     str
dtypes: str(20)
memory usage: 9.5 KB

In [43]:
df.head(10)

,Tên sản phẩm,Giá bán,RAM,Bộ nhớ trong,Kích thước màn hình,Tấm nền,Tần số quét,Độ phân giải,Dung lượng pin,Chip xử lý,Hãng sản xuất,Hệ điều hành,Camera trước,Camera sau,Quay video,Sạc nhanh,Kháng nước / bụi,Trọng lượng,Khuyến mãi giảm giá,URL
0,vivo Y28 8GB 128GB,5.790.000đ,8 GB,128 GB,6.68 inches,LCD,90Hz,1608 × 720 pixels,6000 mAh,Helio G85 (12nm),Vivo,"Android 14, Funtouch OS 14","8 MP, f/2.05","Chính 50 MP, f/1.8 Phụ 2 MP, f/2.4","HD 720p@30fps, FullHD 1080p@30fps",Sạc nhanh 44W,IP64,199g,Tiết kiệm lên đến 58.000đ cho Smember,https://cellphones.com.vn/dien-thoai-vivo-y28....
1,Samsung Galaxy A36 5G 8GB 128GB,7.490.000đ,8 GB,128 GB,6.7 inches,Super AMOLED,120Hz,1080 x 2340 pixels (FullHD+),5000 mAh,Snapdragon 6 Gen 3,Samsung,Android,"12.0 MP, F/2.2","50.0 MP, F/1.8 + 8.0 MP, F/2.2 + 5.0 MP, F/2.4","UHD 4K (3840 x 2160)@30fps, 240fps @HD",Sạc siêu nhanh 45 W,IP67,195 g,Tiết kiệm lên đến 75.000đ cho Smember | Giảm 5...,https://cellphones.com.vn/dien-thoai-samsung-g...
2,Masstel izi T8,530.000đ,NaN,NaN,2.4 inches,NaN,NaN,QVGA 240*320,2300mAh,ASR3603S,Masstel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tiết kiệm lên đến 5.000đ cho Smember,https://cellphones.com.vn/dien-thoai-masstel-i...
3,Samsung Galaxy A21s 6GB,4.690.000đ,6 GB,64 GB,6.5 inches,TFT LCD,NaN,720 x 1600 pixel,"Li-Po 5000 mAh battery, Fast charging 15W",Exynos 850,Samsung,"Android 10, One UI 2.0","13 MP, f/2.2, (wide), 1/3.1"", 1.12µm","48 MP, f/2.0, 26mm (wide), 1/2.0"", 0.8µm, PDAF...",1080p@30fps,Fast charging 15W,NaN,192 g,NaN,https://cellphones.com.vn/samsung-galaxy-a21s-...
4,Samsung Galaxy S20,21.490.000đ,8 GB,128 GB,6.2 inches,"Dynamic AMOLED 2X, 120Hz(1080p), HDR, Gorilla ...",120Hz,3200 x 1440 pixel,"Li-Po 4000 mAh, Sạc nhanh 25W, Sạc không dây 15W",Exynos 990 (7 nm+),Samsung,Android 10.0; One UI 2,"10 MP, f/2.2, 26mm (wide), 1/3.2"", 1.22µm, Dua...","Camera chính: 12 MP, f/1.8, 26mm (wide), Dual ...","Sau: 3240p@30fps, 2160p@30/60fps, 1080p@30/60/...",Sạc nhanh 25W,NaN,163 g,NaN,https://cellphones.com.vn/samsung-galaxy-s20.html
5,OPPO A6t 4GB 64GB,4.390.000đ,4 GB,64 GB,6.75 inches,LCD,120Hz,NaN,6100mAh,Qualcomm Snapdragon 685,OPPO,"ColorOS 15, nền tảng Android 15","5MP, f/2.2","13MP + QVGA, f/2.2 + f/3.0",NaN,Sạc 15W,IP64,~ 205g,Tiết kiệm lên đến 44.000đ cho Smember | Giảm 3...,https://cellphones.com.vn/dien-thoai-oppo-a6t....
6,ASUS ROG Phone 6 16GB 512GB,16.990.000đ,16 GB,512 GB,6.78 inches,AMOLED,Từ 144Hz trở lên,1080 x 2448 pixels (FullHD+),6000 mAh,Snapdragon® 8+ Gen 1,ASUS,Android 12,12 MP,"Camera chính góc rộng: 50 MP, f/1.9, PDAF Came...","8K@24fps, 4K@30/60/120fps, 1080p@30/60/120/240...",Sạc nhanh 65W Sạc ngược 10W Power Delivery 3.0...,IPX4,NaN,Tiết kiệm lên đến 170.000đ cho Smember,https://cellphones.com.vn/asus-rog-phone-6.html
7,Nubia V80 Max 8GB 128GB,3.890.000đ,8 GB,128 GB,6.9 inches,IPS LCD,120Hz,NaN,6000 mAh,Unisoc T7250,Nubia,Android,16 MP,50 MP + 2 MP + 0.08 MP,NaN,Sạc nhanh 22.5W,NaN,NaN,Tiết kiệm lên đến 39.000đ cho Smember | Chi th...,https://cellphones.com.vn/dien-thoai-nubia-v80...
8,Xiaomi 15 5G 12GB 512GB,19.290.000đ,12 GB,512 GB,6.36 inches,CrystalRes AMOLED,120Hz,2670 x 1200 pixels,5240 mAh,Snapdragon 8 Elite (Tiến trình sản xuất 3nm),Xiaomi,Xiaomi HyperOS 2,"Camera trước: 32MP, ƒ/2.0, 90°, Tiêu cự 21mm","Camera chính Leica: 50MP, ƒ/1.62, OIS, Tiêu cự...",(HDR và Dolby Vision) Quay video 8K@24/30fps Q...,Sạc 90W HyperCharge Sạc không dây 50W Hỗ trợ Q...,Kháng nước & bụi chuẩn IP68,191g,Tiết kiệm lên đến 193.000đ cho Smember | Giảm ...,https://cellphones.com.vn/dien-thoai-xiaomi-15...
9,Xiaomi Redmi Note 13 Pro 4G 8GB 128GB,4.690.000đ,8 GB,128 GB,6.67 inches,AMOLED,120Hz,1080 x 2400 pixels (FullHD+),5000 mAh,MediaTek Helio G99-Ultra 8 nhân,Xiaomi,Android 13,16 MP,"Chính 200 MP & Phụ 8 MP, 2 MP",FullHD 1080p@60/30fps HD 720p@30fps,Sạc nhanh 67 W,IP54,188 g,Tiết kiệm lên đến 47.000đ cho Smember | Giảm 6...,https://cellphones.com.vn/xiaomi-redmi-note-13...

In [44]:
df['Khuyến mãi giảm giá'].value_counts()

Khuyến mãi giảm giá
Tiết kiệm lên đến 58.000đ cho Smember                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Tiết kiệm lên đến 75.000đ cho Smember | Giảm 5% | Voucher 5% | Tối đa 1 triệu cho sản phẩm có hiển thị voucher | Trả góp 0% lãi suất qua Ví trả sau MoMo, kỳ hạn 9 tháng | Giảm thêm 10% cho Loa, Tai nghe, PC, Điện máy (từ 10 triệu), Tablet khi mua Điện thoại/Laptop                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Tiết kiệm lên đến 5.000đ cho Smember                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Tiết kiệm lên đến 44.000đ cho Smember | Giảm 3% | Voucher 3% | Tối đa 300k cho điện thoại có hiển thị voucher | Giảm 10% | Tối đa 600k | Dành cho các sản phẩm có hiển thị voucher | Mua điện thoại OPPO nhận PMH500K mua OPPO Pad 5 & Oppo Watch S | Tặng Phiếu mua Tai nghe TWS Oppo trị giá 200,000đ | Tặng Sim/Esim 5G VNSKY, có ngay 3GB data/ngày+500 phút gọi Mobifone & VNSKY, miễn phí 30 ngày đầu - chỉ áp dụng tại cửa hàng | Chi thêm 150K - Nhận ngay dịch vụ Bảo hành Vip 12 tháng 1 đổi 1 tại CellphoneS                                                                                                                                                                                                                                                                                                                                  1
Tiết kiệm lên đến 170.000đ cho Smember                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Tiết kiệm lên đến 39.000đ cho Smember | Chi thêm 150K - Nhận ngay dịch vụ Bảo hành Vip 12 tháng 1 đổi 1 tại CellphoneS | Tặng Sim/Esim 5G VNSKY, có ngay 3GB data/ngày+500 phút gọi Mobifone & VNSKY, miễn phí 30 ngày đầu - chỉ áp dụng tại cửa hàng                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Tiết kiệm lên đến 193.000đ cho Smember | Giảm 6% | Voucher 6% | Tối đa 1 triệu cho sản phẩm có hiển thị voucher | Giảm thêm 500.000Đ cho MTB Xiaomi - Poco khi mua cùng bất kỳ Điện thoại Xiaomi | Tặng phiếu mua hàng trị giá lên đến 300.000đ khi mua kèm Tai nghe Buds 8 Pro/8 Active | Giảm thêm 10% cho Pin dự phòng - Camera - Gia dụng - Sức khỏe Làm đẹp - Đồng hồ trẻ em khi mua Điện thoại/Laptop | Hotsale từ ngày 15/05 - 18/05 : Giảm giá chỉ còn 19,290,000đ (số lượng có hạn, áp dụng cùng ưu đãi Smember). | Ngày cuối hotsale chỉ áp dụng thanh toán online 100% hoặc thanh toán trực tiếp tại cửa hàng.                                                                                                                                                                                                                                1
Tiết kiệm lên đến 47.000đ cho Smember | Giảm 6% | Voucher 6% | Tối đa 1 triệu cho sản phẩm có hiển thị voucher | Giảm thêm 500.000Đ cho MTB Xiaomi - Poco khi mua cùng bất kỳ Điện thoại Xiaomi | Tặng phiếu mua hàng trị giá lên đến 300.000đ khi mua kèm Tai nghe Buds 8 Pro/8 Active | Giảm thêm 10% cho Pin dự phòng - Camera - Gia dụng - Sức khỏe Làm đẹp - Đồng hồ trẻ em khi mua Điện thoại/Laptop                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Tiết kiệm lên đến 442.000đ cho Smember | Giảm 10% | Tối đa 600k | Dành cho các sản phẩm có hiển thị voucher | Giảm đến 2.000.000đ khi tham gia thu cũ lên đời - Thu cũ tốt nhất thị trường | Tặng gói OPPO Premium Serivce trị giá 2 triệu: Bảo hành quốc tế, Bảo hành tận nhà & Gói dịch vụ chăm sóc cao cấp 2 lần/năm | Mua điện thoại OPPO nhận PMH500K mua OPPO Pad 5 & Oppo Watch S | Tặng Oppo Care trị giá 6 triệu: 24 tháng bảo hành & 12 tháng rơi vỡ màn hình | Tặng Phiếu mua Tai nghe TWS Oppo trị giá 200,000đ | Giảm thêm 10% cho Pin dự phòng - Camera - Gia dụng - Sức khỏe Làm đẹp - Đồng hồ trẻ em khi mua Điện thoại/Laptop | Tặng Sim/Esim 5G VNSKY, có ngay 3GB data/ngày+500 phút gọi Mobifone & VNSKY, miễn phí 30 ngày đầu - chỉ áp dụng tại cửa hàng | Nhận thêm 1 trong các khuyến mãi sau: | Tặng phiếu mua hàng 2.000.000    1
Name: count, dtype: int64

In [20]:
df1 = pd.read_csv(URL_FINAL_PATH)

In [21]:
df1

                                              URL_Final
0          https://cellphones.com.vn/honor-magic-5.html
1     https://cellphones.com.vn/xiaomi-redmi-note-12...
2         https://cellphones.com.vn/tecno-spark-8p.html
3     https://cellphones.com.vn/dien-thoai-honor-pla...
4           https://cellphones.com.vn/vivo-iqoo-z6.html
...                                                 ...
1000  https://cellphones.com.vn/dien-thoai-xiaomi-14...
1001   https://cellphones.com.vn/vivo-x90-pro-plus.html
1002  https://cellphones.com.vn/tecno-camon-20-pro-5...
1003  https://cellphones.com.vn/samsung-galaxy-z-fol...
1004       https://cellphones.com.vn/tecno-spark-7.html

[1005 rows x 1 columns]

In [16]:
import pandas as pd

def check_null_values(df1):
    # Tính tổng số giá trị null trong mỗi cột
    null_count = df1.isnull().sum()
    # Tính tỷ lệ phần trăm null (%)
    null_percentage = (df1.isnull().sum() / len(df1)) * 100
    
    # Tạo một DataFrame để hiển thị kết quả cho đẹp
    null_report = pd.DataFrame({
        'Số lượng Null': null_count,
        'Tỷ lệ (%)': null_percentage
    })
    
    # Sắp xếp theo thứ tự giảm dần của số lượng Null
    return null_report.sort_values(by='Số lượng Null', ascending=False)

# Sử dụng hàm cho df1 của bạn
result = check_null_values(df1)
print(result)

                     Số lượng Null  Tỷ lệ (%)
Quay video                       4  36.363636
Kháng nước / bụi                 4  36.363636
Khuyến mãi giảm giá              3  27.272727
Độ phân giải                     3  27.272727
Trọng lượng                      3  27.272727
Sạc nhanh                        3  27.272727
Tần số quét                      2  18.181818
RAM                              1   9.090909
Bộ nhớ trong                     1   9.090909
Tấm nền                          1   9.090909
Hệ điều hành                     1   9.090909
Camera trước                     1   9.090909
Camera sau                       1   9.090909
Tên sản phẩm                     0   0.000000
Hãng sản xuất                    0   0.000000
Giá bán                          0   0.000000
Chip xử lý                       0   0.000000
Dung lượng pin                   0   0.000000
Kích thước màn hình              0   0.000000
URL                              0   0.000000

In [22]:
len(df1)

1005